.\" 
.TH "KBibTeX" "1" "27 February 2011" "KDE" "KDE Application"
.SH "NAME"
KBibTeX \- a BibTeX editor for KDE

.SH "SYNOPSIS"
.B kbibtex
[\fIQt\-options\fR] [\fIKDE\-options\fR] [\fIfile\fR]
.SH "DESCRIPTION"
KBibTeX is a BibTeX editor for KDE written by Thomas Fischer and released under the GPL version 2 or later.

KBibTeX can be started as a stand\-alone program or embedded as a KPart into virtually every KDE program (e.g. Konqueror).

.SH "AUTHOR"
Thomas Fischer <fischer@unix\-ag.uni\-kl.de>

.SH "SEE ALSO"
.BR bibtex "(1)"
.PP 
Visit the \fBKBibTeX\fR homepage at: 
.I http://home.gna.org/kbibtex/

.SH "BUGS"
For more information on how to report bugs, please go to: 
.I http://home.gna.org/kbibtex/bugs.html

