# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/ki18n': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kitemviews': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kservice': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kwallet': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/extra-cmake-modules': '@stable'
